name: Create Release from Artifact

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact from last successful workflow
        uses: actions/download-artifact@v4
        with:
          name: nodejs-25.0.0-pre-riscv64-linux.tar.gz
          run-id: 14   # Hardcoded workflow run ID
          path: ${{ github.workspace }}

      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag 25.0.0-pre
          git push origin 25.0.0-pre

      - name: Create Release
        id: create-release
        uses: actions/create-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 25.0.0-pre
          release_name: "Scheduled Release 2025-09-04, Version 25.0.0-pre"
          body: |
            Node.js 25.0.0-pre built for RISC-V 64-bit architecture

            Platform: linux-riscv64
            Version: 25.0.0-pre
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/nodejs-25.0.0-pre-riscv64-linux.tar.gz
          asset_name: nodejs-25.0.0-pre-riscv64-linux.tar.gz
          asset_content_type: application/gzip
